version: '3.8'

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: "bank"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
  api:
    container_name: "bank_api"
    build: .
    ports:
      - "8080:8080"
    restart: on-failure
    depends_on:
      - db
    volumes:
      - .:/app/
networks:
  default: